Repository yahoo/elide, pull requests merged in 2021-03, with the labels that each got.

#1883 bump jetty to 9.4.38.v20210224 for CVE-2020-27223
  pom.xml
Labels: dependencies

#1884 bump versions
  elide-spring/pom.xml
  pom.xml
Labels: dependencies

#1896 Refactor legacy hooks
  elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityBinding.java
  elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
  elide-core/src/main/java/com/yahoo/elide/core/filter/Operator.java
  elide-core/src/main/java/com/yahoo/elide/core/security/checks/Check.java
  elide-core/src/main/java/com/yahoo/elide/core/security/checks/FilterExpressionCheck.java
  elide-core/src/main/java/com/yahoo/elide/core/security/checks/UserCheck.java
  elide-core/src/main/java/com/yahoo/elide/core/security/executors/ActivePermissionExecutor.java
  elide-core/src/main/java/com/yahoo/elide/core/security/permissions/PermissionCondition.java
  elide-core/src/main/java/com/yahoo/elide/core/security/permissions/expressions/CheckExpression.java
  elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LegacyTestModel.java
  elide-core/src/test/java/com/yahoo/elide/core/lifecycle/LifeCycleTest.java
  elide-core/src/test/java/com/yahoo/elide/core/security/PermissionExecutorTest.java
  elide-core/src/test/java/example/TestCheckMappings.java
  elide-datastore/elide-datastore-hibernate/src/main/java/com/yahoo/elide/core/filter/FilterTranslator.java
Labels: ready for review

#1944 issue 1904 - fix lombok build warnings
  elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ExportControllerProperties.java
  elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/JsonApiControllerProperties.java
  elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/SwaggerControllerProperties.java
Labels: HackTogether

#1948 [HackTogether]Fix Lombok EqualsAndHashCode warnings
  elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQuery.java
  elide-async/src/main/java/com/yahoo/elide/async/models/AsyncQueryResult.java
  elide-async/src/main/java/com/yahoo/elide/async/models/TableExport.java
  elide-async/src/main/java/com/yahoo/elide/async/models/TableExportResult.java
Labels: HackTogether

#1484 Sonar integration
  pom.xml
  screwdriver.yaml
  sonar-project.properties
Labels: ready for review

#1951 Elide graphql javadoc warning fixes
  elide-graphql/src/main/java/com/yahoo/elide/graphql/Entity.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/Environment.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/GraphQLConversionUtils.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/ModelBuilder.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/MutableGraphQLInputObjectType.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/parser/GraphQLEntityProjectionMaker.java
  elide-graphql/src/test/java/example/Pseudonym.java
  elide-graphql/src/test/java/example/package-info.java
  elide-graphql/src/test/java/graphqlEndpointTestModels/Incident.java
Labels: HackTogether

#1947 diamonds to reduce duplication
  elide-async/src/main/java/com/yahoo/elide/async/operation/JSONAPIAsyncQueryOperation.java
  elide-async/src/main/java/com/yahoo/elide/async/service/dao/DefaultAsyncAPIDAO.java
  elide-async/src/main/java/com/yahoo/elide/async/service/thread/AsyncAPICancelRunnable.java
  elide-async/src/test/java/com/yahoo/elide/async/export/formatter/CSVExportFormatterTest.java
  elide-async/src/test/java/com/yahoo/elide/async/export/formatter/JSONExportFormatterTest.java
  elide-async/src/test/java/com/yahoo/elide/async/operation/GraphQLAsyncQueryOperationTest.java
  elide-async/src/test/java/com/yahoo/elide/async/service/thread/AsyncAPICancelRunnableTest.java
  elide-core/src/main/java/com/yahoo/elide/ElideSettingsBuilder.java
  elide-core/src/main/java/com/yahoo/elide/utils/HeaderUtils.java
  elide-core/src/test/java/com/yahoo/elide/core/dictionary/EntityDictionaryTest.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/NamedParamPreparedStatement.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/framework/SQLUnitTest.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/DruidExplainQueryTest.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/H2ExplainQueryTest.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/HiveExplainQueryTest.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/MySQLExplainQueryTest.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PostgresExplainQueryTest.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/PrestoDBExplainQueryTest.java
  elide-datastore/elide-datastore-hibernate/src/test/java/com/yahoo/elide/datastores/hibernate/hql/AbstractHQLQueryBuilderTest.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/MutableGraphQLInputObjectType.java
  elide-graphql/src/main/java/com/yahoo/elide/graphql/PersistentResourceFetcher.java
  elide-graphql/src/test/java/com/yahoo/elide/graphql/GraphQLEndpointTest.java
  elide-integration-tests/src/test/java/com/yahoo/elide/async/integration/tests/framework/AsyncIntegrationTestApplicationResourceConfig.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigSchemaValidator.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/DBConfig.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/ElideDBConfig.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/ElideSecurityConfig.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/ElideTableConfig.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
  elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAsyncConfiguration.java
  elide-spring/elide-spring-boot-autoconfigure/src/main/java/com/yahoo/elide/spring/config/ElideAutoConfiguration.java
  elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideResourceConfig.java
  elide-standalone/src/main/java/com/yahoo/elide/standalone/config/ElideStandaloneSettings.java
Labels: ready for review

#1945 Issue 1929 - define function as lambda
  elide-async/src/main/java/com/yahoo/elide/async/resources/ExportApiEndpoint.java
  elide-async/src/main/java/com/yahoo/elide/async/service/storageengine/FileResultStorageEngine.java
  elide-core/src/main/java/com/yahoo/elide/Elide.java
  elide-core/src/main/java/com/yahoo/elide/core/datastore/inmemory/InMemoryStoreTransaction.java
  elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityBinding.java
  elide-core/src/main/java/com/yahoo/elide/core/dictionary/EntityDictionary.java
  elide-core/src/main/java/com/yahoo/elide/core/filter/dialect/RSQLFilterDialect.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStoreTransaction.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/SQLQueryEngine.java
  elide-graphql/src/test/java/com/yahoo/elide/graphql/PersistentResourceFetcherTest.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/ElideTableConfig.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Named.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
  elide-swagger/src/main/java/com/yahoo/elide/swagger/resources/DocEndpoint.java
Labels: ready for review

#1967 updated README with elide intro video
  README.md
Labels: HackTogether

#1970 elide-datastore-aggregation: Fix build warnings
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/timegrains/Time.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/example/PlayerStats.java
Labels: HackTogether

#1972 Fix elide-model-config javadoc warnings
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigHelpers.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/DynamicConfigSchemaValidator.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Dimension.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Measure.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/model/Table.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/validator/DynamicConfigValidator.java
  elide-model-config/src/main/java/com/yahoo/elide/modelconfig/verify/DynamicConfigVerifier.java
Labels: HackTogether

#1966 Fix javadoc to remove warnings
  elide-test/src/main/java/com/yahoo/elide/test/graphql/GraphQLDSL.java
  elide-test/src/main/java/com/yahoo/elide/test/graphql/elements/Argument.java
  elide-test/src/main/java/com/yahoo/elide/test/graphql/elements/Arguments.java
  elide-test/src/main/java/com/yahoo/elide/test/graphql/elements/VariableDefinitions.java
  elide-test/src/main/java/com/yahoo/elide/test/jsonapi/elements/PatchOperation.java
  elide-test/src/test/java/com/yahoo/elide/test/graphql/GraphQLDSLTest.java
Labels: HackTogether

#1963 elide-datastore-aggregation - fix javadoc build warning
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryEngine.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/QueryValidator.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/ColumnMeta.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/DimensionFormula.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/MetricFormula.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/annotation/TableMeta.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/JoinPath.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/QueryLogger.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/QueryResponse.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/core/Slf4jQueryLogger.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/MetaDataStore.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/metadata/models/Column.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/ColumnProjection.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Optimizer.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/query/Queryable.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/NamedParamPreparedStatement.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromSubquery.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/FromTable.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/annotation/VersionQuery.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/dialects/SQLDialect.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/DynamicSQLReferenceTable.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceTable.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/metadata/SQLReferenceVisitor.java
  elide-datastore/elide-datastore-aggregation/src/main/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/query/SQLColumnProjection.java
  elide-datastore/elide-datastore-aggregation/src/test/java/com/yahoo/elide/datastores/aggregation/queryengines/sql/QueryEngineTest.java
Labels: HackTogether
